import org.apache.spark.sql.functions._
import org.apache.spark.sql.DataFrame
import org.apache.spark.sql.Column


object SparkWithTest extends App with SparkSessionWrapper {

  import spark.implicits._
  spark.conf.set("spark.sql.debug.maxToStringFields", 1000)

  val dataFact = spark.read.json("src/main/resources/data/countries.json")

  println(dataFact
    .select("languages")
    .schema)

  def getReadableLanguage(field: Column): Column = {
    return when(field.isNotNull, array_union(col("lang_arr"), lit(array(field)))).otherwise($"lang_arr")
  }

  def getLanguagesRating(df: DataFrame): DataFrame = {
    df.withColumn("Country", $"name".getItem("common"))
      .withColumn("lang_arr", array())
      .withColumn("lang_arr", getReadableLanguage($"languages.eng"))
      .withColumn("lang_arr", getReadableLanguage($"languages.afr"))
      .withColumn("lang_arr", getReadableLanguage($"languages.amh"))
      .withColumn("lang_arr", getReadableLanguage($"languages.ara"))
      .withColumn("lang_arr", getReadableLanguage($"languages.arc"))
      .withColumn("lang_arr", getReadableLanguage($"languages.aym"))
      .withColumn("lang_arr", getReadableLanguage($"languages.aze"))
      .withColumn("lang_arr", getReadableLanguage($"languages.bar"))
      .withColumn("lang_arr", getReadableLanguage($"languages.bel"))
      .withColumn("lang_arr", getReadableLanguage($"languages.ben"))
      .withColumn("lang_arr", getReadableLanguage($"languages.ber"))
      .withColumn("lang_arr", getReadableLanguage($"languages.bis"))
      .withColumn("lang_arr", getReadableLanguage($"languages.bjz"))
      .withColumn("lang_arr", getReadableLanguage($"languages.bos"))
      .withColumn("lang_arr", getReadableLanguage($"languages.bul"))
      .withColumn("lang_arr", getReadableLanguage($"languages.bwg"))
      .withColumn("lang_arr", getReadableLanguage($"languages.cal"))
      .withColumn("lang_arr", getReadableLanguage($"languages.cat"))
      .withColumn("lang_arr", getReadableLanguage($"languages.ces"))
      .withColumn("lang_arr", getReadableLanguage($"languages.cha"))
      .withColumn("lang_arr", getReadableLanguage($"languages.ckb"))
      .withColumn("lang_arr", getReadableLanguage($"languages.cmn"))
      .withColumn("lang_arr", getReadableLanguage($"languages.crs"))
      .withColumn("lang_arr", getReadableLanguage($"languages.dan"))
      .withColumn("lang_arr", getReadableLanguage($"languages.deu"))
      .withColumn("lang_arr", getReadableLanguage($"languages.div"))
      .withColumn("lang_arr", getReadableLanguage($"languages.dzo"))
      .withColumn("lang_arr", getReadableLanguage($"languages.ell"))
      .withColumn("lang_arr", getReadableLanguage($"languages.eng"))
      .withColumn("lang_arr", getReadableLanguage($"languages.est"))
      .withColumn("lang_arr", getReadableLanguage($"languages.eus"))
      .withColumn("lang_arr", getReadableLanguage($"languages.fao"))
      .withColumn("lang_arr", getReadableLanguage($"languages.fas"))
      .withColumn("lang_arr", getReadableLanguage($"languages.fij"))
      .withColumn("lang_arr", getReadableLanguage($"languages.fil"))
      .withColumn("lang_arr", getReadableLanguage($"languages.fin"))
      .withColumn("lang_arr", getReadableLanguage($"languages.fra"))
      .withColumn("lang_arr", getReadableLanguage($"languages.gil"))
      .withColumn("lang_arr", getReadableLanguage($"languages.gle"))
      .withColumn("lang_arr", getReadableLanguage($"languages.glg"))
      .withColumn("lang_arr", getReadableLanguage($"languages.glv"))
      .withColumn("lang_arr", getReadableLanguage($"languages.grn"))
      .withColumn("lang_arr", getReadableLanguage($"languages.gsw"))
      .withColumn("lang_arr", getReadableLanguage($"languages.hat"))
      .withColumn("lang_arr", getReadableLanguage($"languages.heb"))
      .withColumn("lang_arr", getReadableLanguage($"languages.her"))
      .withColumn("lang_arr", getReadableLanguage($"languages.hgm"))
      .withColumn("lang_arr", getReadableLanguage($"languages.hif"))
      .withColumn("lang_arr", getReadableLanguage($"languages.hin"))
      .withColumn("lang_arr", getReadableLanguage($"languages.hmo"))
      .withColumn("lang_arr", getReadableLanguage($"languages.hrv"))
      .withColumn("lang_arr", getReadableLanguage($"languages.hun"))
      .withColumn("lang_arr", getReadableLanguage($"languages.hye"))
      .withColumn("lang_arr", getReadableLanguage($"languages.ind"))
      .withColumn("lang_arr", getReadableLanguage($"languages.isl"))
      .withColumn("lang_arr", getReadableLanguage($"languages.ita"))
      .withColumn("lang_arr", getReadableLanguage($"languages.jam"))
      .withColumn("lang_arr", getReadableLanguage($"languages.jpn"))
      .withColumn("lang_arr", getReadableLanguage($"languages.kal"))
      .withColumn("lang_arr", getReadableLanguage($"languages.kat"))
      .withColumn("lang_arr", getReadableLanguage($"languages.kaz"))
      .withColumn("lang_arr", getReadableLanguage($"languages.kck"))
      .withColumn("lang_arr", getReadableLanguage($"languages.khi"))
      .withColumn("lang_arr", getReadableLanguage($"languages.khm"))
      .withColumn("lang_arr", getReadableLanguage($"languages.kin"))
      .withColumn("lang_arr", getReadableLanguage($"languages.kir"))
      .withColumn("lang_arr", getReadableLanguage($"languages.kon"))
      .withColumn("lang_arr", getReadableLanguage($"languages.kor"))
      .withColumn("lang_arr", getReadableLanguage($"languages.kwn"))
      .withColumn("lang_arr", getReadableLanguage($"languages.lao"))
      .withColumn("lang_arr", getReadableLanguage($"languages.lat"))
      .withColumn("lang_arr", getReadableLanguage($"languages.lav"))
      .withColumn("lang_arr", getReadableLanguage($"languages.lin"))
      .withColumn("lang_arr", getReadableLanguage($"languages.lit"))
      .withColumn("lang_arr", getReadableLanguage($"languages.loz"))
      .withColumn("lang_arr", getReadableLanguage($"languages.ltz"))
      .withColumn("lang_arr", getReadableLanguage($"languages.lua"))
      .withColumn("lang_arr", getReadableLanguage($"languages.mah"))
      .withColumn("lang_arr", getReadableLanguage($"languages.mey"))
      .withColumn("lang_arr", getReadableLanguage($"languages.mfe"))
      .withColumn("lang_arr", getReadableLanguage($"languages.mkd"))
      .withColumn("lang_arr", getReadableLanguage($"languages.mlg"))
      .withColumn("lang_arr", getReadableLanguage($"languages.mlt"))
      .withColumn("lang_arr", getReadableLanguage($"languages.mon"))
      .withColumn("lang_arr", getReadableLanguage($"languages.mri"))
      .withColumn("lang_arr", getReadableLanguage($"languages.msa"))
      .withColumn("lang_arr", getReadableLanguage($"languages.mya"))
      .withColumn("lang_arr", getReadableLanguage($"languages.nau"))
      .withColumn("lang_arr", getReadableLanguage($"languages.nbl"))
      .withColumn("lang_arr", getReadableLanguage($"languages.ndc"))
      .withColumn("lang_arr", getReadableLanguage($"languages.nde"))
      .withColumn("lang_arr", getReadableLanguage($"languages.ndo"))
      .withColumn("lang_arr", getReadableLanguage($"languages.nep"))
      .withColumn("lang_arr", getReadableLanguage($"languages.nfr"))
      .withColumn("lang_arr", getReadableLanguage($"languages.niu"))
      .withColumn("lang_arr", getReadableLanguage($"languages.nld"))
      .withColumn("lang_arr", getReadableLanguage($"languages.nno"))
      .withColumn("lang_arr", getReadableLanguage($"languages.nob"))
      .withColumn("lang_arr", getReadableLanguage($"languages.nor"))
      .withColumn("lang_arr", getReadableLanguage($"languages.nrf"))
      .withColumn("lang_arr", getReadableLanguage($"languages.nso"))
      .withColumn("lang_arr", getReadableLanguage($"languages.nya"))
      .withColumn("lang_arr", getReadableLanguage($"languages.nzs"))
      .withColumn("lang_arr", getReadableLanguage($"languages.oci"))
      .withColumn("lang_arr", getReadableLanguage($"languages.pap"))
      .withColumn("lang_arr", getReadableLanguage($"languages.pau"))
      .withColumn("lang_arr", getReadableLanguage($"languages.pih"))
      .withColumn("lang_arr", getReadableLanguage($"languages.pol"))
      .withColumn("lang_arr", getReadableLanguage($"languages.por"))
      .withColumn("lang_arr", getReadableLanguage($"languages.prs"))
      .withColumn("lang_arr", getReadableLanguage($"languages.pus"))
      .withColumn("lang_arr", getReadableLanguage($"languages.que"))
      .withColumn("lang_arr", getReadableLanguage($"languages.rar"))
      .withColumn("lang_arr", getReadableLanguage($"languages.roh"))
      .withColumn("lang_arr", getReadableLanguage($"languages.ron"))
      .withColumn("lang_arr", getReadableLanguage($"languages.run"))
      .withColumn("lang_arr", getReadableLanguage($"languages.rus"))
      .withColumn("lang_arr", getReadableLanguage($"languages.sag"))
      .withColumn("lang_arr", getReadableLanguage($"languages.sin"))
      .withColumn("lang_arr", getReadableLanguage($"languages.slk"))
      .withColumn("lang_arr", getReadableLanguage($"languages.slv"))
      .withColumn("lang_arr", getReadableLanguage($"languages.smi"))
      .withColumn("lang_arr", getReadableLanguage($"languages.smo"))
      .withColumn("lang_arr", getReadableLanguage($"languages.sna"))
      .withColumn("lang_arr", getReadableLanguage($"languages.som"))
      .withColumn("lang_arr", getReadableLanguage($"languages.sot"))
      .withColumn("lang_arr", getReadableLanguage($"languages.spa"))
      .withColumn("lang_arr", getReadableLanguage($"languages.sqi"))
      .withColumn("lang_arr", getReadableLanguage($"languages.srd"))
      .withColumn("lang_arr", getReadableLanguage($"languages.srp"))
      .withColumn("lang_arr", getReadableLanguage($"languages.ssw"))
      .withColumn("lang_arr", getReadableLanguage($"languages.swa"))
      .withColumn("lang_arr", getReadableLanguage($"languages.swe"))
      .withColumn("lang_arr", getReadableLanguage($"languages.tam"))
      .withColumn("lang_arr", getReadableLanguage($"languages.tet"))
      .withColumn("lang_arr", getReadableLanguage($"languages.tgk"))
      .withColumn("lang_arr", getReadableLanguage($"languages.tha"))
      .withColumn("lang_arr", getReadableLanguage($"languages.tir"))
      .withColumn("lang_arr", getReadableLanguage($"languages.tkl"))
      .withColumn("lang_arr", getReadableLanguage($"languages.toi"))
      .withColumn("lang_arr", getReadableLanguage($"languages.ton"))
      .withColumn("lang_arr", getReadableLanguage($"languages.tpi"))
      .withColumn("lang_arr", getReadableLanguage($"languages.tsn"))
      .withColumn("lang_arr", getReadableLanguage($"languages.tso"))
      .withColumn("lang_arr", getReadableLanguage($"languages.tuk"))
      .withColumn("lang_arr", getReadableLanguage($"languages.tur"))
      .withColumn("lang_arr", getReadableLanguage($"languages.tvl"))
      .withColumn("lang_arr", getReadableLanguage($"languages.ukr"))
      .withColumn("lang_arr", getReadableLanguage($"languages.urd"))
      .withColumn("lang_arr", getReadableLanguage($"languages.uzb"))
      .withColumn("lang_arr", getReadableLanguage($"languages.ven"))
      .withColumn("lang_arr", getReadableLanguage($"languages.vie"))
      .withColumn("lang_arr", getReadableLanguage($"languages.xho"))
      .withColumn("lang_arr", getReadableLanguage($"languages.zdj"))
      .withColumn("lang_arr", getReadableLanguage($"languages.zho"))
      .withColumn("lang_arr", getReadableLanguage($"languages.zib"))
      .withColumn("lang_arr", getReadableLanguage($"languages.zul")) 
      .withColumn("Language", explode($"lang_arr"))
      .groupBy("Language")
      .agg(
        count("*").as("NumCountries"),
        collect_list("Country").as("Countries")
      )
      .orderBy(desc("NumCountries"))
  }

  def getCountriesWithManyBorders(df: DataFrame): DataFrame = {
    df.withColumn("NumBorders", size($"borders"))
      .filter($"NumBorders" >= 5)
      .withColumn("Country", $"name".getItem("common"))
      .withColumn("BorderCountries", concat_ws(",", $"borders"))
      .select("Country", "NumBorders", "BorderCountries")
  }

}
